name: Code Quality

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.7' # Adjust to match your project

      - name: Install StyleCop
        run: dotnet tool install --global dotnet-format

      - name: Run StyleCop
        run: dotnet format --verify-no-changes --verbosity detailed

      - name: Install SonarCloud Scanner
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Run SonarCloud Analysis
        run: dotnet sonarscanner begin /k:"MAbbes-design_Project_EarlyDev" /o:"mabbes-design" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"
      
      - name: Restore dependencies
        run: dotnet restore
      
      - name: Build project
        run: dotnet build --no-restore --configuration Release
      
      - name: Run .NET Code Analysis
        run: dotnet build --no-restore /p:EnableNETAnalyzers=true /p:TreatWarningsAsErrors=true

      - name: End SonarCloud Analysis
        run: dotnet sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
