name: SecOps Pipeline 

on: 
  push: 
    branches: [ "security/*", "feature/*" ] # Runs security checks when pushing to security or feature branches
  pull_request:  
    branches: [ "main" ] # Runs security checks when merging a PR into the main branch

jobs: 
  security_scan: 
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup .NET # Install .NET runtime for security checks
      uses: actions/setup-dotnet@v4      
      with:
        dotnet-version: 8.0.x

    - name: Install Android Workloads
      run: dotnet workload install maui-android

    - name: Restore dependencies
      run: |
         dotnet --version
         dotnet restore 

    - name: Install OWASP Dependency-Check #OWASP Dependency-Check for NuGet Vulnerabilities
      run: |
        wget https://github.com/jeremylong/DependencyCheck/releases/download/v12.1.0/dependency-check-12.1.0-release.zip
        unzip dependency-check-12.1.0-release.zip
        chmod +x dependency-check/bin/dependency-check.sh
        
    - name: Run Dependency-Check with NVD key
      run: ./dependency-check/bin/dependency-check.sh --project "EarlyDevSecurityScan" --out reports --scan /home/runner/work/Project_EarlyDev/Project_EarlyDev --nvdApiKey ${{ secrets.NVD_API_KEY }}

    - name: GitHub Secret Scanning
      uses: github/codeql-action/init@v2
      with:
       languages: 'csharp'
      
    - name: Enforce Security Before Deployment # Blocks merging if vulnerabilities exist in either the .NET packages or OWASP scan
      run: |
        dotnet list package --vulnerable
        if [ $? -ne 0 ]; then
          echo "Vulnerable dependencies detected! Merge blocked."
          exit 1
        fi
        if grep -i "CRITICAL" reports/dependency-check-report.html; then
          echo "Critical vulnerabilities found, Merge will be blocked."
          exit 1
        fi
    
    - name: Complete SecOps Checks # Confirm that all security checks have completed
      run: echo "Security checks completed!"
